### ISSUE TITLE
Add ElectionAdministration

### ISSUE THREAD

**Issue by cjerdonek** [mapmydemocracy/civichackathon#1]
We should add the [ElectionAdministration object](https://github.com/votinginfoproject/vip-specification/blob/a54e26c69828b39ae14d9561959b2d6decd04bc5/vip_spec.xsd#L253), using the information from the Department of Elections web site [here](http://www.sfgov2.org/index.aspx?page=3335).

**Comment by cjerdonek** [comment]
Also, note that the Locality object should reference the ElectionAdministration object.

**Comment by xih** [comment]
I'm working on the ElectionAdministration object.
